config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'cards#index'

  # main routes

  get '/users/:id/account', to: 'main#account', as: 'user_account'
  get '/payments/success', to: 'payments#success', as: 'payment_success'

  # cards routes

  get '/cards/new', to: 'cards#new', as: 'new_card'
  get '/cards/:id/edit', to: 'cards#edit', as: 'edit_card'
  patch '/cards/:id', to: 'cards#update'
  put '/cards/:id', to: 'cards#update'
  get '/cards/:id', to: 'cards#show', as: 'card'
  post '/cards/:id/checkout', to: 'cards#checkout'
  get '/cards', to: 'cards#index', as: 'cards'
  post '/cards', to: 'cards#create'
  delete '/cards/:id', to: 'cards#destroy'

  # offers routes

  get '/offers/new', to: 'offers#new', as: 'new_offer'
  post '/offers', to: 'offers#create'
  get '/offers', to: 'offers#index', as: 'offers_index'
  get '/offers/:id', to: 'offers#show', as: 'offer'
  get '/offers/:id/edit', to: 'offers#edit', as: 'edit_offer'
  patch '/offers/:id', to: 'offers#update'
  put '/offers/:id', to: 'offers#update'
  delete '/offers/:id', to: 'offers#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    has_many :offers, dependent: :destroy
    has_one_attached :card_image
    validates :name, :condition, :price, :qty, :card_image, presence: true

    def self.search(search,user_id=nil)
        if search
            if user_id
                match = Card.where("name ILIKE ? AND user_id = ?", "%#{search}%",user_id)
            else
                match = Card.where("name ILIKE ?", "%#{search}%")
            end
            if match
                match
            else
                flash.now[:errors] = "No matching results for #{search}"
                Card.order('id DESC')
            end
        else
            Card.order('id DESC')
        end
    end
end

app/models/offer.rb
class Offer < ApplicationRecord

  validate :buyer_must_not_be_owner
  #  :seller_must_own_card, 

  belongs_to :buyer, :class_name => 'User'
  belongs_to :seller, :class_name => 'User'
  belongs_to :card

  def buyer_must_not_be_owner
    # card buyer is not the owner
    if self.buyer.id == self.card.user.id
      errors.add(:buyer, "can't buy their own item.")
    end
    puts "buyer: #{self.buyer.id} owner: #{self.card.user.id}"
  end

  def seller_must_own_card
    # seller is the owner
    if self.seller.id != self.card.user.id
      errors.add(:seller, "must own the item.")
    end
    puts "seller: #{self.seller.id} owner: #{self.card.user.id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :password_complexity
  after_initialize :auto_name

  has_many :cards, dependent: :destroy
  has_many :buyer_offers, :class_name => 'Offer', :foreign_key => 'buyer_id'
  has_many :seller_offers, :class_name => 'Offer', :foreign_key => 'seller_id'

  def auto_name
    if self.name == ""
      self.name = self.email.match(/.*(?=@)/)
    end
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,70}$/

    errors.add :password, 'Complexity requirement not met. Length should be 8-70 characters and include: 1 uppercase, 1 lowercase and 1 digit'
  end
end

app/controllers/application_controller.rb
require 'uri'
require 'net/http'

class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def get_logged_in_user
        if user_signed_in?
            @user = current_user
        else
            @user = {
                name: "Guest",
                email: "no email"
            }
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :address, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :address)}
   end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :delete, :edit, :update, :checkout]
    before_action :get_logged_in_user, only: [:new, :index, :show, :create, :edit, :update, :checkout]
    before_action :get_card_from_params, only: [:show, :destroy, :edit, :update, :checkout]
    
    @@card_condition = {
        "NM" => "Near Mint",
        "LP" => "Lightly Played",
        "MP" => "Moderately Played",
        "HP" => "Heavily Played/Damaged"
    }

    def new
        @card = Card.new
    end

    def checkout
        
        if user_signed_in?
            Stripe.api_key = ENV['STRIPE_SECRET']
            session = Stripe::Checkout::Session.create({
                payment_method_types: ['card'],
                customer_email: @user[:email],
                line_items: [{
                    price_data: {
                        currency: 'aud',
                        product_data: {
                            name: @card.name
                        },
                        unit_amount: (@card.price * 100).to_i
                    },
                    quantity: @card.qty
                }],
                mode: 'payment',
                success_url: "#{root_url}payments/success?cardId=#{@card.id}",
                cancel_url: "#{root_url}cards"
            })

            render json: session
            # @session_id = session.id
        end
    end

    def show
        @condition = @@card_condition[@card.condition]
    end

    def index
        @cards = Card.search(params[:search]).page(params[:page])
        @search_path = cards_path
    end

    def edit
        if @card.user != @user
            flash.now[:errors] = "You can't edit another user's listing"
            render action: 'show'
        end
    end

    def update
        if @card.user != @user
            flash.now[:errors] = "You can't edit another user's listing"
            show
            render action: 'show'
        else
            if @card.update(card_params)
                flash.now[:errors] = "Updated successfully"
                show
                render action: 'show'
            else
                flash.now[:errors] = @card.errors.full_messages
                show
                render action: 'show'
            end
        end
    end

    def destroy
        if @card.user == current_user
            @card.destroy
            redirect_to cards_path
        else
            flash.now[:errors] = "You can't delete a card you don't own"
            index
            render action: 'index'
        end
    end

    def create
        @card = Card.new(card_params)
        if @card.save
            redirect_to @card
        else
            flash.now[:errors] = @card.errors.full_messages
            new
            render action: 'new'
        end
    end

    private

    def card_params
        fields = params.require(:card).permit(:name, :price, :condition, :user_id, :qty, :card_image, :search)
        fields[:user] = current_user
        return fields
    end

    def get_card_from_params
        @card = Card.find(params[:id])
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

    before_action :get_cards, only: [:index]

    def index
    end

    def account
        get_logged_in_user
        @user_viewed = User.find(params[:id])
        if params[:search]
            @cards = Card.search(params[:search],@user_viewed.id).page(params[:page])
        else
            @cards = @user_viewed.cards.page(params[:page])
        end
        @search_path = user_account_path(@user_viewed)
    end

    private

    def get_cards
        @cards = Card.order('id DESC')
    end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def success
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/cards/_cards.html.erb
<br>
<div class="w-100">
    <%= form_tag(@search_path, method: :get) do %>
        <span><%= text_field_tag :search, params[:search], placeholder: 'Search listings' %></span>
    <% end %>
    <br>
</div>

<%= paginate @cards %>
<div class="space" id="cards">

    <% @cards.each do |card| %>
        <div class="h-center card">
            <%# TODO replace placeholder for cloudinary image upload %>
            <% if card != nil && card.card_image.attached? %>
                <%= cl_image_tag card.card_image.key, crop: :scale, width: 120, cloud_name: 'bdtech' %>
            <% else %>
                <img src="http://via.placeholder.com/120x180" alt="placeholder image">
            <% end %>
            <div style="text-align: center;">
            <% if card.condition %>
                <span class="<%= card.condition.downcase %> small-text"><%= card.condition %> &nbsp;&nbsp;</span>
            <% end %>
                <span><%= link_to card.name, card_path(card) %></span>
            </div>
            <p>$<%= '%.2f' % card.price %></p>
        </div>
    <% end %>
    
</div>

app/views/cards/_form.html.erb
<%= form_with model: @card, local: true do |f| %>
    <div class="flex-start">
    <%= f.text_field :name, placeholder: "Name", :required => true %>
    </div>
    <br>
    <div class="flex-start">
    <%= f.number_field :price, in: 1.00..100000.00, step: 0.01, placeholder: "Price", :required => true %>
    </div>
    <br>
    <div class="flex-start">
    <%= f.number_field :qty, in: 1..1000000, placeholder: "Quantity", :required => true %>
    </div>
    <h2>Condition:</h2>
    <div class="flex-start">
    <%= f.radio_button :condition, "NM" %>
    <%= f.label :condition_nm, "Near mint" %>
    </div>
    <div class="flex-start">
    <%= f.radio_button :condition, "LP" %>
    <%= f.label :condition_lp, "Lightly played" %>
    </div>
    <div class="flex-start">
    <%= f.radio_button :condition, "MP" %>
    <%= f.label :condition_mp, "Moderately played" %>
    </div>
    <div class="flex-start">
    <%= f.radio_button :condition, "HP" %>
    <%= f.label :condition_hp, "Heavily played/Damaged" %>
    </div>
    <h2>Picture: </h2>
    <div class="flex-start">
    <%= f.file_field :card_image, :required => true %>
    </div>
    <br>


    <%= f.submit %>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit listing for <%= @card.name %></h1>
<br>
<br>
<%= render 'form' %>

app/views/cards/index.html.erb
 <br>
 <h1>Latest listings:</h1>
 <%= render 'cards' %>

app/views/cards/new.html.erb
<br>
<h1>New card listing</h1>
<br>
<%= render 'form' %>

app/views/cards/show.html.erb
<script src="https://js.stripe.com/v3/"></script>

<div class="h-center">
    <h1> <%= @card.name %> </h1>
    <br>
    <% if @card != nil && @card.card_image.attached? %>
        <%= cl_image_tag @card.card_image.key, crop: :scale, width: 173, cloud_name: 'bdtech' %>
    <% else %>
        <img src="http://via.placeholder.com/173x260" alt="placeholder image">
    <% end %>
    <br>
    <p>Condition: <span class="<%= @card.condition.downcase %>"><%= @condition %></span></p>
    <span><p>Price: $<%= '%.2f' % @card.price %> each &nbsp;&nbsp;&nbsp;&nbsp;Quantity: <%= @card.qty %></p></span>
    <p>Listed by: <%= link_to @card.user.name,  user_account_path(@card.user.id) %>
</div>
<br>
<% if @card.user == @user %>
    <div><%= link_to "Edit", edit_card_path(@card) %> | <%= link_to "Delete", @card, method: 'delete', data: {confirm: "Delete #{@card.name}?"} %></div>
<% else %>
    <button id="checkout-button">Buy now</button><span>With cash: $<%= '%.2f' % @card.price %></span>
<% end %>
<br>
<br>
<%= link_to "Back", :back %>

<%# Stripe payment gateway logic %>

<script type="text/javascript">


    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('pk_test_51Iu6sdGQuL01uXfHc9iPJCjUfmiMrjnhcHeYZVyHonpi5qJ4ZCs0ybiPuHdQ3iXrRWwd3ug7DsjuN3qpHCweE5wJ001wx7oTBu');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function() {
        <% if !user_signed_in? %>
            <% session["user_return_to"] = request.url %>
            location = "<%= new_user_session_path %>"
        <% end %>
        <% if @user.address == "" %>
            <% session["user_return_to"] = request.url %>
            <% flash.now[:errors] = "You must have an address to buy items" %>
            location = "<%= edit_user_registration_path %>"
        <% end %>
        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        const csrfToken = document.querySelector("[name='csrf-token']").content
        fetch('/cards/<%= @card.id %>/checkout', {
            method: 'POST',
            headers: {
          'Content-Type': 'application/json',
          "X-CSRF-Token": csrfToken,
        },
        })
        .then(function(response) {
            return response.json();
        })
        .then(function(session) {
            return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function(result) {
            // If `redirectToCheckout` fails due to a browser or network
            // error, you should display the localized error message to your
            // customer using `error.message`.
            if (result.error) {
            alert(result.error.message);
            }
        })
        .catch(function(error) {
            console.error('Error:', error);
        });
    });
</script>




    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tcboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700;900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <ul>
        <li id="headingnav"><%= link_to "TCboard", root_path, { :class => "headingtext"} %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, user_account_path(current_user) %></li>
          <li><%= link_to "New listing", new_card_path(current_user.id) %> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>

  <div class="h-center">
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:errors] %>
    <p class=<% if flash[:color] %>
        <%= flash[:color]%>
      <% else %>
        "error"
      <% end %>> <%= flash[:errors] %> </p>
    <% end %>
  </div>
  <main class="h-center">
    <%= yield %>
  </main>
  </body>
</html>

app/views/main/account.html.erb
<br>
<h1>Listings for <%= @user_viewed.name %></h1>

<% if @user == @user_viewed %>
    <br>
    <%= link_to "Account settings", edit_user_registration_path %>
    <br>
<% end %>

<%= render 'cards/cards' %>

app/views/main/index.html.erb
    <%= render '/cards/cards' %>

app/views/offers/_form.html.erb
<%= form_with model: @offer, local: true do |f| %>
    <%= f.text_field :name, placeholder: "Name" %>

app/views/payments/success.html.erb
<h1>Payment Successful!</h1>

<h2>The seller has been emailed with your name and postal address</h2>
<h3>Tracking details will be emailed to you within 24 hours</h3>
<h3>Contact seller on EMAIL for any queries</h3>

<%= link_to "Back", :back%>